services:
  survey-app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: survey/app
    environment:
      WWWUSER: '${WWWUSER}'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_SESSION: '${XDEBUG_SESSION:-1}'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
      PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-serverName=survey.site}'
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    networks:
      - survey
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - .:/var/www/html
    depends_on:
      survey-mysql:
        condition: service_healthy
      survey-redis:
        condition: service_started

  survey-mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '${DB_FORWARD_PORT:-3306}:3306'
    networks:
      - survey
    volumes:
      - ./docker/db:/var/lib/db
      - survey-mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
      retries: 3
      timeout: 5s
      interval: 5s

  survey-redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_FORWARD_PORT:-6379}:6379'
    networks:
      - survey
    volumes:
      - 'survey-redis:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
      interval: 5s

  survey-nginx:
    image: nginx:stable-alpine
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${APP_SECURE_PORT:-443}:443'
    networks:
      - survey
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - survey-app

networks:
  survey:
    driver: bridge

volumes:
  survey-mysql:
    driver: local
  survey-redis:
    driver: local
